body:
  graph_mode: body
  module_key: body
  kps_index: [0, 1, 2, 5, 6, 7, 8, 9, 10]
  kps_rel_range: [0, 9]
  norm_kps_rel_index: [3, 4]
left_hand:
  graph_mode: hand21
  module_key: left_hand
  kps_index: [91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111]
  kps_rel_range: [9, 30]
  norm_kps_rel_index: [9]
right_hand:
  graph_mode: hand21
  module_key: right_hand
  kps_index: [112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132]
  kps_rel_range: [30, 51]
  norm_kps_rel_index: [30]